{"timestamp":"2025-10-14T18:39:24.791126Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-14T18:39:24.791577Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/ETL_toll_data_python.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-14T18:39:24.813872Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:39:24.813977Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:39:24.814062Z","level":"info","event":"Current task name:download_unzip","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:39:24.814094Z","level":"info","event":"Dag name:ETL_toll_data_python","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:39:24.817650Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"FileExistsError","exc_value":"[Errno 17] File exists: 'output'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/ETL_toll_data_python.py","lineno":17,"name":"download_unzip"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-14T18:39:24.829956Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:39:24.830141Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:39:24.830193Z","level":"info","event":"Task:<Task(PythonOperator): download_unzip>","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:39:24.830225Z","level":"info","event":"Failure caused by [Errno 17] File exists: 'output'","logger":"task.stdout"}
