{"timestamp":"2025-10-14T18:37:46.165446Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-14T18:37:46.165789Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/ETL_toll_data_python.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-14T18:37:46.184278Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:46.184398Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:46.184485Z","level":"info","event":"Current task name:extract_csv","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:46.184540Z","level":"info","event":"Dag name:ETL_toll_data_python","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:46.217415Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"OSError","exc_value":"Cannot save file into a non-existent directory: '/opt/airflow/data/output'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/ETL_toll_data_python.py","lineno":49,"name":"extract_csv_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py","lineno":3902,"name":"to_csv"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py","lineno":1152,"name":"to_csv"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py","lineno":247,"name":"save"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py","lineno":739,"name":"get_handle"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py","lineno":604,"name":"check_parent_directory"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-14T18:37:46.232086Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:46.232263Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:46.232322Z","level":"info","event":"Task:<Task(PythonOperator): extract_csv>","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:46.232361Z","level":"info","event":"Failure caused by Cannot save file into a non-existent directory: '/opt/airflow/data/output'","logger":"task.stdout"}
